name: Dev Release

on:
  push:
    branches:
      - main

jobs:
  release-dev:
    name: Create Dev Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Prepare dev version string
        id: prep_version
        run: |
          BASE_VERSION=$(jq -r .version package.json)
          SHORT_SHA=$(git rev-parse --short HEAD)
          FULL_VERSION="${BASE_VERSION}-dev.${SHORT_SHA}"
          echo "version=${FULL_VERSION}" >> $GITHUB_OUTPUT

      - name: Update package.json for publishing
        run: npm version ${{ steps.prep_version.outputs.version }} --no-git-tag-version

      - name: Publish to npm under dev tag
        run: npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
