name: Dev Release

on:
  push:
    branches:
      - main

jobs:
  prerelease:
    name: Create Dev Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get package version
        id: get_version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Create Prerelease
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          prerelease: true
          tag: "v${{ steps.get_version.outputs.version }}-dev.${{ github.sha }}"
          releaseName: "v${{ steps.get_version.outputs.version }}-dev.${{ github.sha }}"
