# GitHub Action for a scheduled bi-weekly nightly release

name: Release Nightly Version

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    # Runs at 03:00 UTC on the 1st and 15th of every month
    - cron: '0 3 1,15 * *'

jobs:
  publish-nightly:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for versioning

      # Step 2: Set up the Node.js environment.
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      # Step 3: Configure Git user details.
      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 4: Install dependencies.
      - name: Install dependencies
        run: npm ci

      # Step 5: Bump the version, create a commit, and tag it.
      # This creates a pre-release version like 4.1.0-nightly.0
      - name: Bump version and create tag
        run: npm version prerelease --preid=nightly -m "chore(release-nightly): %s"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Push the new commit and tag to the repository branch.
      - name: Push changes to repository
        run: git push --follow-tags

      # Step 7: Publish the package to npm with the 'nightly' tag.
      - name: Publish to npm
        run: npm publish --tag nightly
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
