name: Nightly Release

on:
  schedule:
    # Runs every two weeks on Sunday at midnight UTC
    - cron: '0 0 */14 * 0'
  workflow_dispatch:

jobs:
  release-nightly:
    name: Create Bi-Weekly Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Prepare bi-weekly version string
        id: prep_version
        run: |
          BASE_VERSION=$(jq -r .version package.json)
          BWK_SUFFIX=$(date +%Y%m%d)
          FULL_VERSION="${BASE_VERSION}-bwk.${BWK_SUFFIX}"
          echo "version=${FULL_VERSION}" >> $GITHUB_OUTPUT

      - name: Update package.json for publishing
        run: npm version ${{ steps.prep_version.outputs.version }} --no-git-tag-version

      - name: Publish to npm under nightly tag
        # Note: npm dist-tag is still 'nightly' as requested in docs
        run: npm publish --tag nightly
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
