# .github/workflows/release.yml
name: Stable Release

on:
  workflow_dispatch:
    inputs:
      version-bump:
        type: choice
        description: 'What type of version bump?'
        required: true
        default: 'patch'
        options:
          - patch
          - minor
          - major

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to allow version bump and tagging
      id-token: write # for npm provenance
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We need to fetch all history and branches for versioning
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for commit and tag access

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Bump version and create Git tag
        run: npm version ${{ github.event.inputs.version-bump }} -m "chore(release): stable release %%s"

      - name: Push changes and tags
        run: git push --follow-tags

      - name: Publish to npm
        run: npm publish --tag latest --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
