name: Stable Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Create Stable Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get package version
        id: get_version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: "v${{ steps.get_version.outputs.version }}"
          releaseName: "v${{ steps.get_version.outputs.version }}"